import { CaseRecord, Pathway } from '@/types/case';

export const DEMO_CASE: CaseRecord = {
  id: 'case-ccu-2026-08',
  title: 'IBEDC Disputed Estimated Billing & Uncredited Payment',
  citizenName: 'Adebayo Olatunji',
  accountReference: '0456789123',
  provider: 'IBEDC (Ibadan Electricity Distribution Company) — Abeokuta Business Unit',
  firstReportOutcome: 'Response didn’t resolve it',
  createdAt: '14 August 2026',
  updatedAt: '17 September 2026',
  isCompleted: false,
  evidence: [
    {
      id: 'doc-01',
      title: 'Electricity Bill — July 2026',
      filename: '01_IBEDC_July2026_Bill.pdf',
      type: 'pdf',
      uploadDate: '12 Aug 2026',
      pageCount: 1,
      size: '184 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Bill for July 2026 totaling ₦64,438.50. Explicitly notes: "Estimated billing applied. Actual meter reading not available."',
      fileReference: 'IBEDC Bill July 2026',
      keyFields: [
        { label: 'Customer', value: 'Adebayo Olatunji' },
        { label: 'Account No.', value: '0456789123' },
        { label: 'Meter No.', value: '5432109876' },
        { label: 'Total Due', value: '₦64,438.50' },
        { label: 'Due Date', value: '15 August 2026' },
        { label: 'Note', value: 'Estimated billing applied. Actual meter reading not available.' },
      ],
      fullSnippet: 'IBEDC — Ibadan Electricity Distribution Company\nCustomer Electricity Bill\nCustomer Name: Adebayo Olatunji\nAccount Number: 0456789123\nMeter Number: 5432109876\nAddress: 12, Alagbon Close, Abeokuta, Ogun State\nBilling Period: 01 July 2026 – 31 July 2026\nPrevious Balance: ₦18,450.00\nCurrent Charges: ₦42,780.00\nVAT (7.5%): ₦3,208.50\nTotal Amount Due: ₦64,438.50\nDue Date: 15 August 2026\nNote: Estimated billing applied. Actual meter reading not available.',
    },
    {
      id: 'doc-02',
      title: 'Payment Receipt — 12 August 2026',
      filename: '02_Payment_Receipt_12Aug.png',
      type: 'receipt',
      uploadDate: '12 Aug 2026',
      pageCount: 1,
      size: '92 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Successful payment of ₦64,438.50 via USSD *322# payment gateway for Account 0456789123.',
      fileReference: 'IBEDC Payment Gateway',
      keyFields: [
        { label: 'Transaction Ref', value: 'TRX-IBEDC-982341' },
        { label: 'Date', value: '12 August 2026, 14:22' },
        { label: 'Amount Paid', value: '₦64,438.50' },
        { label: 'Account', value: '0456789123' },
        { label: 'Channel', value: 'USSD *322#' },
        { label: 'Status', value: 'Successful' },
      ],
      fullSnippet: 'Payment Successful\nTransaction Reference: TRX-IBEDC-982341\nDate: 12 August 2026, 14:22\nAmount Paid: ₦64,438.50\nAccount: 0456789123\nChannel: USSD *322#\nStatus: Successful\nIBEDC Payment Gateway • Keep this receipt for your records',
    },
    {
      id: 'doc-03',
      title: 'Complaint Email to IBEDC Customer Care',
      filename: '03_Complaint_Email_14Aug.pdf',
      type: 'email',
      uploadDate: '14 Aug 2026',
      pageCount: 1,
      size: '142 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Formal dispute email sent to customer.care@ibedc.com detailing that the physical meter is functional, normal consumption is far lower, and attached proof of payment.',
      fileReference: 'Email Message',
      keyFields: [
        { label: 'From', value: 'adebayo.olatunji@gmail.com' },
        { label: 'To', value: 'customer.care@ibedc.com' },
        { label: 'Date', value: '14 August 2026, 09:47' },
        { label: 'Subject', value: 'Wrong Estimated Billing — Account 0456789123' },
      ],
      fullSnippet: 'From: adebayo.olatunji@gmail.com\nTo: customer.care@ibedc.com\nDate: 14 August 2026, 09:47\nSubject: Wrong Estimated Billing — Account 0456789123\n\nDear IBEDC Customer Care,\nI am writing to complain about the bill for July 2026. My meter is working and I have been paying regularly. The current bill of ₦64,438.50 is far higher than my normal consumption. I have attached the payment receipt for the previous bill. Please investigate and correct this estimated charge.\nAccount: 0456789123 | Meter: 5432109876 | Phone: 0803 456 7890\nThank you, Adebayo',
    },
    {
      id: 'doc-04',
      title: 'IBEDC Automated Acknowledgement Notice',
      filename: '04_Acknowledgement_16Aug.png',
      type: 'image',
      uploadDate: '16 Aug 2026',
      pageCount: 1,
      size: '115 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Official acknowledgement issuing Complaint Reference CCU-12345, stating an officer will respond within 5–7 working days.',
      fileReference: 'IBEDC Customer Care Portal',
      keyFields: [
        { label: 'Reference', value: 'CCU-12345' },
        { label: 'Date Received', value: '14 August 2026' },
        { label: 'Status', value: 'Received and under review' },
        { label: 'Response SLA', value: '5–7 working days' },
      ],
      fullSnippet: 'IBEDC Customer Care\nComplaint Reference: CCU-12345\nDate Received: 14 August 2026\nStatus: Received and under review\n\nDear Customer, Your complaint regarding estimated billing has been received. A customer service officer will contact you within 5–7 working days.\nThank you for contacting IBEDC.',
    },
    {
      id: 'doc-05',
      title: 'IBEDC Technical Review Letter',
      filename: '05_IBEDC_Response_Letter_21Aug.pdf',
      type: 'letter',
      uploadDate: '22 Aug 2026',
      pageCount: 1,
      size: '156 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Letter from Customer Care Officer, Abeokuta Business Unit, stating the technical team is reviewing consumption and instructing customer to continue making payments to avoid disconnection.',
      fileReference: 'IBEDC Abeokuta Business Unit',
      keyFields: [
        { label: 'Date', value: '21 August 2026' },
        { label: 'Ref', value: 'CCU-12345' },
        { label: 'Signatory', value: 'Customer Care Officer, Abeokuta Business Unit' },
      ],
      fullSnippet: 'IBEDC Customer Care Unit — Abeokuta Business Unit\n21 August 2026\nRe: Complaint Reference CCU-12345 | Account: 0456789123\nDear Mr Adebayo Olatunji,\nWe acknowledge receipt of your complaint dated 14 August 2026 concerning estimated billing. Our technical team is currently reviewing your meter and consumption pattern. We will update you once the investigation is concluded.\nPlease continue to make payments to avoid disconnection while the matter is under review.\nYours faithfully, Customer Care Officer',
    },
    {
      id: 'doc-06',
      title: 'IBEDC Formal Resolution Letter',
      filename: '09_IBEDC_Closure_Letter_03Sep.pdf',
      type: 'letter',
      uploadDate: '04 Sep 2026',
      pageCount: 1,
      size: '162 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Letter from Customer Care Supervisor claiming the investigation concluded, adjustments were effected, and no further action is required.',
      fileReference: 'IBEDC Abeokuta Business Unit',
      keyFields: [
        { label: 'Date', value: '3 September 2026' },
        { label: 'Ref', value: 'CCU-12345' },
        { label: 'Claim', value: '"Matter has been resolved... adjustments have been effected"' },
      ],
      fullSnippet: 'IBEDC Customer Care Unit — Abeokuta Business Unit\n3 September 2026\nRe: Complaint Reference CCU-12345 | Account: 0456789123\nDear Mr Adebayo Olatunji,\nFollowing our investigation into your complaint of 14 August 2026, we are pleased to inform you that the matter has been resolved. Your account has been reviewed and the necessary adjustments have been effected. No further action is required from your end.\nYours faithfully, Customer Care Supervisor',
    },
    {
      id: 'doc-07',
      title: 'WhatsApp Follow-up with IBEDC Care',
      filename: '06_WhatsApp_Followup_07Sep.png',
      type: 'chat',
      uploadDate: '08 Sep 2026',
      pageCount: 1,
      size: '98 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Chat on 7 September where Adebayo notes the new bill arrived with high charges; IBEDC contradicts their 3 September letter by saying the complaint is "still under review".',
      fileReference: 'WhatsApp Messenger Screenshot',
      keyFields: [
        { label: 'Chat Date', value: '07 September 2026' },
        { label: 'Citizen Message', value: '"My complaint CCU-12345 is still not resolved. The new bill has come again with the same high charge."' },
        { label: 'IBEDC Care Reply', value: '"Your complaint is still under review. We will get back to you soon."' },
      ],
      fullSnippet: 'IBEDC Care WhatsApp Chat\n07/09/2026, 11:24 — Adebayo: "Good morning. My complaint CCU-12345 is still not resolved. The new bill has come again with the same high charge. Please update me."\n07/09/2026, 14:03 — IBEDC Care: "Good afternoon sir. Your complaint is still under review. We will get back to you soon."',
    },
    {
      id: 'doc-08',
      title: 'Electricity Bill — August 2026',
      filename: '07_IBEDC_August2026_Bill.pdf',
      type: 'pdf',
      uploadDate: '10 Sep 2026',
      pageCount: 1,
      size: '190 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'August 2026 bill totaling ₦106,492.50. Demonstrates that the previous ₦64,438.50 payment was never credited to balance, and estimated billing continues.',
      fileReference: 'IBEDC Bill August 2026',
      keyFields: [
        { label: 'Previous Balance', value: '₦64,438.50 (Uncredited)' },
        { label: 'Current Charges', value: '₦39,120.00' },
        { label: 'Total Due', value: '₦106,492.50' },
        { label: 'Due Date', value: '15 September 2026' },
        { label: 'Note', value: 'Estimated billing continues. Meter reading still pending.' },
      ],
      fullSnippet: 'IBEDC — Ibadan Electricity Distribution Company\nCustomer Electricity Bill\nCustomer Name: Adebayo Olatunji\nAccount Number: 0456789123\nMeter Number: 5432109876\nAddress: 12, Alagbon Close, Abeokuta, Ogun State\nBilling Period: 01 August 2026 – 31 August 2026\nPrevious Balance: ₦64,438.50\nCurrent Charges: ₦39,120.00\nVAT (7.5%): ₦2,934.00\nTotal Amount Due: ₦106,492.50\nDue Date: 15 September 2026\nNote: Estimated billing continues. Meter reading still pending.',
    },
    {
      id: 'doc-09',
      title: 'Audio Transcript — Citizen Statement',
      filename: '08_Voice_Note_Transcript_17Sep.txt',
      type: 'voicenote',
      uploadDate: '17 Sep 2026',
      pageCount: 1,
      size: '2 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      contentSummary: 'Voice note recorded by Adebayo summarizing that despite claims of resolution, no credit was received, billing remains estimated, and the case must be escalated.',
      fileReference: 'Voice Note Audio (28 sec)',
      keyFields: [
        { label: 'Speaker', value: 'Adebayo Olatunji' },
        { label: 'Date', value: '17 September 2026' },
        { label: 'Duration', value: '28 seconds' },
      ],
      fullSnippet: 'Voice Note Transcript — 17 September 2026\nSpeaker: Adebayo Olatunji\n"Hello. This is Adebayo again. I complained since August about the high estimated bill. They said it was under review. Now they are saying the matter is resolved, but my latest bill still has the same problem. I have not received any corrected bill or credit. The light is still irregular and the charge is still wrong. I need this taken to the next level."',
    },
  ],
  events: [
    {
      id: 'ev-01',
      date: '2026-07-31',
      displayDate: '31 July 2026',
      title: 'Estimated bill of ₦64,438.50 issued by IBEDC',
      description: 'IBEDC issued an estimated bill for July 2026 without an actual physical meter reading, charging ₦42,780 current charges plus previous balance.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-01'],
      sourceNames: ['01_IBEDC_July2026_Bill.pdf'],
      verifiedByUser: true,
      category: 'billing',
    },
    {
      id: 'ev-02',
      date: '2026-08-12',
      displayDate: '12 August 2026',
      title: 'Payment of ₦64,438.50 made via USSD gateway',
      description: 'Citizen paid the full amount of ₦64,438.50 under transaction reference TRX-IBEDC-982341 prior to the 15 August due date.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-02'],
      sourceNames: ['02_Payment_Receipt_12Aug.png'],
      verifiedByUser: true,
      category: 'payment',
    },
    {
      id: 'ev-03',
      date: '2026-08-14',
      displayDate: '14 August 2026',
      title: 'Formal dispute filed via email to IBEDC Customer Care',
      description: 'Citizen emailed customer.care@ibedc.com stating the physical meter is functional, estimated billing is unjustified, and attached proof of payment.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-03'],
      sourceNames: ['03_Complaint_Email_14Aug.pdf'],
      verifiedByUser: true,
      category: 'complaint',
    },
    {
      id: 'ev-04',
      date: '2026-08-14',
      displayDate: '14 August 2026',
      title: 'IBEDC assigned Complaint Reference CCU-12345',
      description: 'Automated portal confirmed receipt of complaint and promised a customer service officer contact within 5–7 working days.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-04'],
      sourceNames: ['04_Acknowledgement_16Aug.png'],
      verifiedByUser: true,
      category: 'response',
    },
    {
      id: 'ev-05',
      date: '2026-08-21',
      displayDate: '21 August 2026',
      title: 'IBEDC Customer Care Unit letter: technical review ongoing',
      description: 'IBEDC Abeokuta Business Unit acknowledged complaint, stated technical team is reviewing the meter, and advised customer to keep paying to avoid disconnection.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-05'],
      sourceNames: ['05_IBEDC_Response_Letter_21Aug.pdf'],
      verifiedByUser: true,
      category: 'response',
    },
    {
      id: 'ev-06',
      date: '2026-09-03',
      displayDate: '03 September 2026',
      title: 'IBEDC Supervisor letter: claims matter is resolved & adjusted',
      description: 'IBEDC Customer Care Supervisor claimed account was reviewed, necessary adjustments were effected, and no further action is required.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-06'],
      sourceNames: ['09_IBEDC_Closure_Letter_03Sep.pdf'],
      verifiedByUser: true,
      category: 'response',
    },
    {
      id: 'ev-07',
      date: '2026-09-07',
      displayDate: '07 September 2026',
      title: 'Sources Conflict: IBEDC WhatsApp states "still under review"',
      description: 'When citizen asked on WhatsApp why the new bill arrived unadjusted, IBEDC Care stated CCU-12345 was "still under review" — directly contradicting the 03 September closure letter.',
      provenance: 'conflict',
      provenanceLabel: 'Sources conflict',
      sourceIds: ['doc-06', 'doc-07'],
      sourceNames: ['09_IBEDC_Closure_Letter_03Sep.pdf', '06_WhatsApp_Followup_07Sep.png'],
      conflictDetails: 'IBEDC Abeokuta official letter dated 03 September states "the matter has been resolved and necessary adjustments have been effected", but IBEDC WhatsApp agent on 07 September states "Your complaint is still under review. We will get back to you soon."',
      verifiedByUser: true,
      category: 'communication',
    },
    {
      id: 'ev-08',
      date: '2026-09-10',
      displayDate: '10 September 2026',
      title: 'August bill issued showing ₦106,492.50 with payment uncredited',
      description: 'August bill shows the previous ₦64,438.50 payment was never reflected in the balance, and estimated billing was applied again without a meter reading.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-08'],
      sourceNames: ['07_IBEDC_August2026_Bill.pdf'],
      verifiedByUser: true,
      category: 'billing',
    },
    {
      id: 'ev-09',
      date: '2026-09-17',
      displayDate: '17 September 2026',
      title: 'Citizen voice note: power supply is irregular & charges incorrect',
      description: 'Citizen recorded a statement affirming the physical meter remains functional, power supply in Alagbon Close is irregular, no credit has been received, and the issue requires escalation.',
      provenance: 'user-reported',
      provenanceLabel: 'You said this',
      sourceIds: ['doc-09'],
      sourceNames: ['08_Voice_Note_Transcript_17Sep.txt'],
      verifiedByUser: true,
      notes: 'Citizen statement regarding power supply frequency and lack of physical visit by IBEDC technicians.',
      category: 'status',
    },
    {
      id: 'ev-10',
      date: '2026-09-20',
      displayDate: 'Current Status',
      title: 'Problem remains unresolved despite internal company closure',
      description: 'Estimated billing continues to compound, ₦64,438.50 payment remains uncredited, and customer faces risk of disconnection despite full prior payment.',
      provenance: 'needs-review',
      provenanceLabel: 'Needs review',
      sourceIds: [],
      sourceNames: [],
      verifiedByUser: false,
      category: 'status',
    },
  ],
  unresolved: {
    problem: 'IBEDC continues to apply excessive arbitrary estimated billing (₦106,492.50 outstanding) to Account 0456789123 with a working physical meter. The payment of ₦64,438.50 made on 12 August was never credited, and IBEDC issued a closure letter claiming the issue was resolved while simultaneously stating on WhatsApp that it remains under review.',
    alreadyTried: '1. Paid July bill in full (₦64,438.50 via USSD).\n2. Submitted formal email dispute on 14 Aug (Ref: CCU-12345).\n3. Received technical review letter on 21 Aug promising investigation.\n4. Followed up on WhatsApp on 07 Sep after receiving higher August bill.',
    responseReceived: 'IBEDC issued conflicting responses: a formal letter on 03 September claiming the matter was resolved with adjustments effected, yet an official WhatsApp response on 07 September stating the complaint remains "under review", while the actual August bill shows no adjustment and double-counts the paid balance.',
    resolutionVision: '1. Immediate reconciliation and crediting of the ₦64,438.50 payment made on 12 August.\n2. Cancellation of arbitrary estimated billing charges for July and August.\n3. Physical reading and calibration of the installed functional meter (Meter No: 5432109876).\n4. A stay on any disconnection order while the case is being handled.',
    requestedAction: 'Requesting the receiving institution/advocate to review the verified chronology, intervene with IBEDC management, and order a physical meter inspection and account reconciliation under NERC Customer Service Standards Regulations.',
  },
  selectedPathways: ['nerc-forum-abeokuta'],
};

export const RELEVANT_PATHWAYS: Pathway[] = [
  {
    id: 'nerc-forum-abeokuta',
    name: 'NERC Consumer Complaints Forum Office (Abeokuta)',
    organization: 'Nigerian Electricity Regulatory Commission (NERC)',
    jurisdiction: 'Ogun State / Ibadan DisCo Jurisdiction',
    whyRelevant: 'NERC regulations mandate that when an electricity distribution company fails to resolve a billing dispute within 15 days or issues conflicting closure notices, the customer may appeal directly to the independent NERC Forum Office.',
    eligibility: 'Must have already submitted a complaint to the DisCo (IBEDC), obtained a reference number (CCU-12345), and waited more than 15 days without satisfactory resolution.',
    requiredDocuments: [
      'Proof of complaint to IBEDC (Email & Acknowledgement CCU-12345)',
      'Disputed electricity bills (July & August 2026)',
      'Proof of payment (Receipt TRX-IBEDC-982341)',
      'IBEDC response letters & conflicting WhatsApp transcript',
    ],
    officialSource: 'NERC Customer Complaints Handling: Standards and Procedures Regulations (Section 7)',
    sourceUrl: 'https://nerc.gov.ng',
    lastCheckedDate: 'September 2026',
    warning: 'May be relevant. NERC Forum Offices hold quasi-judicial hearings; verify current filing hours and whether hearings are virtual or in-person at Abeokuta.',
  },
  {
    id: 'fccpc-consumer-protection',
    name: 'FCCPC (Federal Competition & Consumer Protection Commission)',
    organization: 'FCCPC Nigeria',
    jurisdiction: 'National / Southwest Zonal Office',
    whyRelevant: 'FCCPC investigates deceptive business practices, unjust estimated billing, and failure to honor paid consumer transactions under the Federal Competition and Consumer Protection Act 2018.',
    eligibility: 'Any consumer subjected to arbitrary billing, double charging, or refusal to rectify proven payments.',
    requiredDocuments: [
      'Evidence of paid transaction not credited',
      'Correspondence showing company claimed resolution without doing so',
      'Account and meter details',
    ],
    officialSource: 'FCCPC Consumer Complaints Portal (FCCPA 2018 Section 17 & 130)',
    sourceUrl: 'https://fccpc.gov.ng',
    lastCheckedDate: 'September 2026',
    warning: 'May be relevant. FCCPC can mediate or issue regulatory summons if the service provider ignored earlier commitments.',
  },
  {
    id: 'legal-aid-civic-advocate',
    name: 'Community Legal Aid & Civic Consumer Advocacy',
    organization: 'Legal Aid Council / Civic Consumer Rights Initiative',
    jurisdiction: 'Abeokuta / Ogun State Branch',
    whyRelevant: 'Civil society organizations and legal aid caseworkers provide direct representation for low-income citizens facing wrongful utility disconnection.',
    eligibility: 'Open to residents experiencing persistent utility harassment, wrongful disconnection threats, or administrative neglect.',
    requiredDocuments: [
      'Complete CaseCarry Carry-Forward Bundle',
      'National ID / Voter card copy (optional)',
      'Utility account notice',
    ],
    officialSource: 'Legal Aid Council of Nigeria Act & Civic Rights Charter',
    lastCheckedDate: 'September 2026',
    warning: 'May be relevant. Caseworker availability varies by local branch.',
  },
];

export const SAMPLE_CASE_RECORD = DEMO_CASE;
export const SAMPLE_EVIDENCE_FILES = DEMO_CASE.evidence;
export const SAMPLE_CASE_EVENTS = DEMO_CASE.events;
export const SAMPLE_UNRESOLVED_ISSUE = DEMO_CASE.unresolved;
export const SAMPLE_PATHWAYS = RELEVANT_PATHWAYS;
