import { CaseRecord, Pathway } from '@/types/case';

export const DEMO_CASE: CaseRecord = {
  id: 'case-demo-ogun-2026',
  title: 'IBEDC Disputed Estimated Billing & Uncredited Payment',
  citizenName: 'Adebayo Olatunji (Fictional Example)',
  accountReference: '0456-DEMO-789123',
  provider: 'IBEDC (Ibadan Electricity Distribution Company) — Abeokuta Business Unit',
  firstReportOutcome: 'Response didn’t resolve it',
  createdAt: '14 August 2026',
  updatedAt: '17 September 2026',
  isCompleted: false,
  isDemo: true,
  status: 'verified',
  contradictions: [
    'IBEDC formal letter (03 Sept) stated the dispute was resolved and adjustments effected, but IBEDC WhatsApp care (07 Sept) stated the complaint CCU-12345 remained "under review".',
    'IBEDC billing ledger shows July payment of ₦64,438.50 was not credited, yet August bill doubled the arrears under estimated billing despite a functional physical meter being present.',
  ],
  missingInformation: [
    'Physical meter calibration report from IBEDC technical team has not been provided to the customer.',
    'Bank transaction reversal proof from the payment switch has not been issued to confirm whether payment remained with Interswitch/IBEDC.',
  ],
  evidence: [
    {
      id: 'doc-01',
      title: 'Electricity Bill — July 2026',
      filename: '01_IBEDC_July2026_Bill.pdf',
      type: 'pdf',
      uploadDate: '12 Aug 2026',
      pageCount: 1,
      size: '184 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'Bill for July 2026 totaling ₦64,438.50. Explicitly notes: "Estimated billing applied. Actual meter reading not available."',
      fileReference: 'IBEDC Bill July 2026',
      keyFields: [
        { label: 'Customer', value: 'Adebayo Olatunji (Sample)' },
        { label: 'Account No.', value: '0456-DEMO-789123' },
        { label: 'Meter No.', value: '5432-DEMO-9876' },
        { label: 'Total Due', value: '₦64,438.50' },
        { label: 'Due Date', value: '15 August 2026' },
        { label: 'Note', value: 'Estimated billing applied. Actual meter reading not available.' },
      ],
      fullSnippet: 'IBEDC — Ibadan Electricity Distribution Company [Fictional Sample Document]\nCustomer Electricity Bill\nCustomer Name: Adebayo Olatunji (Sample)\nAccount Number: 0456-DEMO-789123\nMeter Number: 5432-DEMO-9876\nAddress: 12, Fictional Street, Abeokuta, Ogun State\nBilling Period: 01 July 2026 – 31 July 2026\nPrevious Balance: ₦18,450.00\nCurrent Charges: ₦42,780.00\nVAT (7.5%): ₦3,208.50\nTotal Amount Due: ₦64,438.50\nDue Date: 15 August 2026\nNote: Estimated billing applied. Actual meter reading not available.',
    },
    {
      id: 'doc-02',
      title: 'Payment Receipt — 12 August 2026',
      filename: '02_Payment_Receipt_12Aug.png',
      type: 'receipt',
      uploadDate: '12 Aug 2026',
      pageCount: 1,
      size: '92 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'Successful payment of ₦64,438.50 via USSD *322# payment gateway for Account 0456-DEMO-789123.',
      fileReference: 'IBEDC Payment Gateway',
      keyFields: [
        { label: 'Transaction Ref', value: 'TRX-DEMO-982341' },
        { label: 'Date', value: '12 August 2026, 14:22' },
        { label: 'Amount Paid', value: '₦64,438.50' },
        { label: 'Account', value: '0456-DEMO-789123' },
        { label: 'Channel', value: 'USSD *322#' },
        { label: 'Status', value: 'Successful' },
      ],
      fullSnippet: 'Payment Successful [Fictional Sample]\nTransaction Reference: TRX-DEMO-982341\nDate: 12 August 2026, 14:22\nAmount Paid: ₦64,438.50\nAccount: 0456-DEMO-789123\nChannel: USSD *322#\nStatus: Successful\nIBEDC Payment Gateway • Keep this receipt for your records',
    },
    {
      id: 'doc-03',
      title: 'Complaint Email to IBEDC Customer Care',
      filename: '03_Complaint_Email_14Aug.pdf',
      type: 'email',
      uploadDate: '14 Aug 2026',
      pageCount: 1,
      size: '142 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'Formal dispute email sent to customer.care@ibedc.com detailing that the physical meter is functional, normal consumption is far lower, and attached proof of payment.',
      fileReference: 'Email Message',
      keyFields: [
        { label: 'From', value: 'citizen.sample@example.com' },
        { label: 'To', value: 'customer.care@ibedc.com' },
        { label: 'Date', value: '14 August 2026, 09:47' },
        { label: 'Subject', value: 'Wrong Estimated Billing — Account 0456-DEMO-789123' },
      ],
      fullSnippet: 'From: citizen.sample@example.com\nTo: customer.care@ibedc.com\nDate: 14 August 2026, 09:47\nSubject: Wrong Estimated Billing — Account 0456-DEMO-789123\n\nDear IBEDC Customer Care,\nI am writing to complain about the bill for July 2026. My meter is working and I have been paying regularly. The current bill of ₦64,438.50 is far higher than my normal consumption. I have attached the payment receipt for the previous bill. Please investigate and correct this estimated charge.\nAccount: 0456-DEMO-789123 | Meter: 5432-DEMO-9876 | Phone: 0800-000-DEMO\nThank you, Adebayo',
    },
    {
      id: 'doc-04',
      title: 'IBEDC Automated Acknowledgement Notice',
      filename: '04_Acknowledgement_16Aug.png',
      type: 'image',
      uploadDate: '16 Aug 2026',
      pageCount: 1,
      size: '115 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'Official acknowledgement issuing Complaint Reference CCU-12345, stating an officer will respond within 5–7 working days.',
      fileReference: 'IBEDC Customer Care Portal',
      keyFields: [
        { label: 'Reference', value: 'CCU-12345' },
        { label: 'Date Received', value: '14 August 2026' },
        { label: 'Status', value: 'Received and under review' },
        { label: 'Response SLA', value: '5–7 working days' },
      ],
      fullSnippet: 'IBEDC Customer Care [Sample Document]\nComplaint Reference: CCU-12345\nDate Received: 14 August 2026\nStatus: Received and under review\n\nDear Customer, Your complaint regarding estimated billing has been received. A customer service officer will contact you within 5–7 working days.\nThank you for contacting IBEDC.',
    },
    {
      id: 'doc-05',
      title: 'IBEDC Technical Review Letter',
      filename: '05_IBEDC_Response_Letter_21Aug.pdf',
      type: 'letter',
      uploadDate: '22 Aug 2026',
      pageCount: 1,
      size: '156 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'Letter from Customer Care Officer, Abeokuta Business Unit, stating the technical team is reviewing consumption and instructing customer to continue making payments to avoid disconnection.',
      fileReference: 'IBEDC Abeokuta Business Unit',
      keyFields: [
        { label: 'Date', value: '21 August 2026' },
        { label: 'Ref', value: 'CCU-12345' },
        { label: 'Signatory', value: 'Customer Care Officer, Abeokuta Business Unit' },
      ],
      fullSnippet: 'IBEDC Customer Care Unit — Abeokuta Business Unit [Sample]\n21 August 2026\nRe: Complaint Reference CCU-12345 | Account: 0456-DEMO-789123\nDear Mr Adebayo Olatunji,\nWe acknowledge receipt of your complaint dated 14 August 2026 concerning estimated billing. Our technical team is currently reviewing your meter and consumption pattern. We will update you once the investigation is concluded.\nPlease continue to make payments to avoid disconnection while the matter is under review.\nYours faithfully, Customer Care Officer',
    },
    {
      id: 'doc-06',
      title: 'IBEDC Formal Resolution Letter',
      filename: '06_IBEDC_Closure_Letter_03Sep.pdf',
      type: 'letter',
      uploadDate: '04 Sep 2026',
      pageCount: 1,
      size: '168 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'Letter claiming matter CCU-12345 has been investigated and resolved with bill adjustment effected on the system. (Contradicts actual subsequent bill).',
      fileReference: 'IBEDC Head of Customer Operations',
      keyFields: [
        { label: 'Date', value: '03 September 2026' },
        { label: 'Outcome', value: 'Resolved — Bill Adjustment Effected' },
        { label: 'Status Claimed', value: 'Closed' },
      ],
      fullSnippet: 'IBEDC Customer Operations — Abeokuta Business Hub\n03 September 2026\nNotice of Complaint Resolution — Ref: CCU-12345\nDear Customer,\nFollowing technical appraisal of Account 0456-DEMO-789123, appropriate adjustments have been effected to your account to reconcile estimated consumption. The issue is hereby considered resolved and closed on our customer dispute registry.\nThank you for your patience.\nHead, Customer Complaints Resolution',
    },
    {
      id: 'doc-07',
      title: 'Subsequent Electricity Bill — August 2026',
      filename: '07_IBEDC_August2026_Bill.pdf',
      type: 'pdf',
      uploadDate: '06 Sep 2026',
      pageCount: 1,
      size: '190 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'August bill issued showing ₦106,492.50 due. Uncredited previous payment of ₦64,438.50 and continuing estimated billing with zero adjustments.',
      fileReference: 'IBEDC Bill August 2026',
      keyFields: [
        { label: 'Arrears Carried Over', value: '₦64,438.50 (Uncredited)' },
        { label: 'Current Charge', value: '₦42,054.00' },
        { label: 'Total Due', value: '₦106,492.50' },
        { label: 'Adjustment Shown', value: '₦0.00' },
      ],
      fullSnippet: 'IBEDC Customer Bill — August 2026 [Sample Document]\nAccount: 0456-DEMO-789123 | Customer: Adebayo Olatunji\nPrevious Balance (Uncredited): ₦64,438.50\nCurrent Month Estimated Consumption: ₦39,120.00\nVAT: ₦2,934.00\nTotal Payable: ₦106,492.50\nNotice: Disconnection warning active if arrears are not cleared within 10 days.',
    },
    {
      id: 'doc-08',
      title: 'IBEDC WhatsApp Chat Transcript',
      filename: '08_WhatsApp_Support_Chat_07Sep.png',
      type: 'chat',
      uploadDate: '07 Sep 2026',
      pageCount: 1,
      size: '138 KB',
      processingStatus: 'processed',
      privacyStatus: 'included',
      isOriginalRetained: true,
      contentSummary: 'WhatsApp support conversation on 07 September where agent stated CCU-12345 is "still under review by billing department", directly contradicting the 03 September closure letter.',
      fileReference: 'IBEDC Verified WhatsApp Support',
      keyFields: [
        { label: 'Date', value: '07 September 2026, 11:15' },
        { label: 'Agent', value: 'IBEDC Care Bot / Agent Zainab' },
        { label: 'Statement', value: 'Ticket CCU-12345 is pending review by billing department.' },
      ],
      fullSnippet: '[07/09/2026, 11:12] Adebayo: Good morning. I got August bill of ₦106k but you sent letter saying CCU-12345 was resolved and adjusted. My ₦64k payment is still missing.\n[07/09/2026, 11:15] IBEDC Care: Hello Adebayo, thank you for reaching out. Checking our system... Ticket CCU-12345 is still pending review by the billing team in Ibadan. Please bear with us while adjustments are processed.\n[07/09/2026, 11:17] Adebayo: But I have a letter from Abeokuta Hub dated 3 September saying it is already closed and resolved!\n[07/09/2026, 11:20] IBEDC Care: The update has not reflected on the billing server. Kindly disregard closure letter until server update is complete.',
    },
  ],
  events: [
    {
      id: 'ev-01',
      date: '2026-07-31',
      displayDate: '31 July 2026',
      datePrecision: 'exact',
      title: 'IBEDC issued July estimated bill for ₦64,438.50',
      description: 'Customer Adebayo Olatunji received July electricity bill with arbitrary estimated charge of ₦64,438.50 despite installed meter 5432-DEMO-9876 being functional.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-01'],
      sourceNames: ['01_IBEDC_July2026_Bill.pdf'],
      sourceQuote: 'Total Amount Due: ₦64,438.50. Note: Estimated billing applied.',
      verifiedByUser: true,
      category: 'billing',
    },
    {
      id: 'ev-02',
      date: '2026-08-12',
      displayDate: '12 August 2026',
      datePrecision: 'exact',
      title: 'Citizen paid ₦64,438.50 in full via USSD gateway',
      description: 'Payment was completed via USSD *322# payment gateway with transaction reference TRX-DEMO-982341 to avoid wrongful utility disconnection.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-02'],
      sourceNames: ['02_Payment_Receipt_12Aug.png'],
      sourceQuote: 'Transaction Reference: TRX-DEMO-982341. Amount Paid: ₦64,438.50. Status: Successful.',
      verifiedByUser: true,
      category: 'payment',
    },
    {
      id: 'ev-03',
      date: '2026-08-14',
      displayDate: '14 August 2026',
      datePrecision: 'exact',
      title: 'Formal complaint submitted to customer.care@ibedc.com',
      description: 'Citizen emailed formal dispute requesting meter inspection, adjustment of estimated charges, and crediting of the 12 August payment.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-03'],
      sourceNames: ['03_Complaint_Email_14Aug.pdf'],
      sourceQuote: 'My meter is working and I have been paying regularly. The current bill of ₦64,438.50 is far higher than my normal consumption.',
      verifiedByUser: true,
      category: 'complaint',
    },
    {
      id: 'ev-04',
      date: '2026-08-16',
      displayDate: '16 August 2026',
      datePrecision: 'exact',
      title: 'IBEDC issued ticket CCU-12345 promising review in 5–7 days',
      description: 'Automated notification confirmed receipt of billing complaint and assigned official tracking ticket CCU-12345.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-04'],
      sourceNames: ['04_Acknowledgement_16Aug.png'],
      sourceQuote: 'Complaint Reference: CCU-12345. A customer service officer will contact you within 5–7 working days.',
      verifiedByUser: true,
      category: 'communication',
    },
    {
      id: 'ev-05',
      date: '2026-08-21',
      displayDate: '21 August 2026',
      datePrecision: 'exact',
      title: 'IBEDC letter promised technical review & warned against non-payment',
      description: 'Customer Care Officer confirmed technical team appraisal was underway and instructed the customer to keep paying bills to prevent disconnection.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-05'],
      sourceNames: ['05_IBEDC_Response_Letter_21Aug.pdf'],
      sourceQuote: 'Our technical team is currently reviewing your meter and consumption pattern.',
      verifiedByUser: true,
      category: 'response',
    },
    {
      id: 'ev-06',
      date: '2026-09-03',
      displayDate: '03 September 2026',
      datePrecision: 'exact',
      title: 'IBEDC issued resolution notice claiming bill adjustment effected',
      description: 'Head of Customer Operations issued formal letter stating complaint CCU-12345 was resolved, adjustments effected, and case closed on the dispute registry.',
      provenance: 'conflict',
      provenanceLabel: 'Sources conflict',
      sourceIds: ['doc-06', 'doc-07', 'doc-08'],
      sourceNames: ['06_IBEDC_Closure_Letter_03Sep.pdf', '08_WhatsApp_Support_Chat_07Sep.png'],
      sourceQuote: 'Appropriate adjustments have been effected... The issue is hereby considered resolved and closed.',
      conflictDetails: 'IBEDC closure letter claims dispute is closed and adjustments effected, but August bill shows zero adjustment, and WhatsApp support on 07 Sept confirms complaint remains unadjusted and pending on billing servers.',
      verifiedByUser: true,
      category: 'status',
    },
    {
      id: 'ev-07',
      date: '2026-09-06',
      displayDate: '06 September 2026',
      datePrecision: 'exact',
      title: 'August bill issued with ₦106,492.50 due; July payment uncredited',
      description: 'IBEDC issued August bill ignoring the 12 August payment of ₦64,438.50, adding another estimated charge of ₦42,054.00, and issuing a disconnection warning.',
      provenance: 'source-backed',
      provenanceLabel: 'Source-backed',
      sourceIds: ['doc-07'],
      sourceNames: ['07_IBEDC_August2026_Bill.pdf'],
      sourceQuote: 'Previous Balance (Uncredited): ₦64,438.50. Total Payable: ₦106,492.50.',
      verifiedByUser: true,
      category: 'billing',
    },
    {
      id: 'ev-08',
      date: '2026-09-07',
      displayDate: '07 September 2026',
      datePrecision: 'exact',
      title: 'IBEDC WhatsApp support stated complaint is still pending review',
      description: 'Support representative stated CCU-12345 is still pending review by billing department in Ibadan, explicitly instructing the citizen to disregard the 03 September closure letter.',
      provenance: 'conflict',
      provenanceLabel: 'Sources conflict',
      sourceIds: ['doc-08', 'doc-06'],
      sourceNames: ['08_WhatsApp_Support_Chat_07Sep.png', '06_IBEDC_Closure_Letter_03Sep.pdf'],
      sourceQuote: 'Ticket CCU-12345 is still pending review... Kindly disregard closure letter until server update is complete.',
      conflictDetails: 'Direct contradiction between official written closure letter and official WhatsApp support channel.',
      verifiedByUser: true,
      category: 'communication',
    },
  ],
  unresolved: {
    problem: 'IBEDC continues to apply excessive arbitrary estimated billing (₦106,492.50 outstanding) to Account 0456-DEMO-789123 with a working physical meter. The payment of ₦64,438.50 made on 12 August was never credited, and IBEDC issued a closure letter claiming the issue was resolved while simultaneously stating on WhatsApp that it remains under review.',
    originalIssue: 'Wrong estimated billing on Account 0456-DEMO-789123 despite installed functional meter 5432-DEMO-9876, and uncredited payment.',
    whatWasRequested: '1. Reconciliation and crediting of ₦64,438.50 payment made on 12 August.\n2. Cancellation of arbitrary estimated charges.\n3. Physical inspection and reading of installed functional meter.\n4. Reversal of disconnection threat.',
    whatHappened: 'Citizen paid July bill in full and submitted complaint CCU-12345. IBEDC promised 5-7 days turnaround, sent a letter claiming it was resolved and adjusted, but issued an August bill with zero credit and doubled arrears, while WhatsApp support stated the matter was still pending.',
    responseReceived: 'Conflicting responses: 03 Sept closure letter claimed resolution, but 07 Sept WhatsApp support stated complaint is still pending review and to disregard the closure letter.',
    whatWasResolved: 'IBEDC acknowledged receipt of complaint and assigned Reference CCU-12345.',
    whatWasNotResolved: 'Payment of ₦64,438.50 has not been credited; arbitrary estimated billing continues; physical meter has not been read or calibrated; disconnection warning remains active.',
    resolutionVision: '1. Immediate reconciliation and crediting of the ₦64,438.50 payment made on 12 August.\n2. Cancellation of arbitrary estimated billing charges for July and August.\n3. Physical reading and calibration of the installed functional meter.\n4. A stay on any disconnection order while the case is being handled.',
    requestedAction: 'Requesting the receiving institution/advocate to review the verified chronology, intervene with IBEDC management, and order account reconciliation under consumer protection standards.',
    alreadyTried: '1. Paid July bill in full (₦64,438.50 via USSD).\n2. Submitted formal email dispute on 14 Aug (Ref: CCU-12345).\n3. Received technical review letter on 21 Aug promising investigation.\n4. Followed up on WhatsApp on 07 Sep after receiving higher August bill.',
  },
  selectedPathways: ['ogserc-consumer-dispute', 'fccpc-consumer-protection'],
};

export const RELEVANT_PATHWAYS: Pathway[] = [
  {
    id: 'ogserc-consumer-dispute',
    name: 'Ogun State Electricity Regulatory Commission (OGSERC) — Consumer Disputes Unit',
    organization: 'Ogun State Electricity Regulatory Commission / Ministry of Energy',
    jurisdiction: 'Ogun State, Nigeria',
    pathwayType: 'sector_regulator',
    whyRelevant: 'Your case concerns an unresolved electricity estimated billing dispute with IBEDC in Ogun State. The supplied records show you paid ₦64,438.50, lodged complaint CCU-12345, but received conflicting closure communications while arrears increased to ₦106,492.50 under disconnection threat.',
    relevanceReason: 'Strong match based on Ogun State jurisdiction, IBEDC provider, and closure letter failure in record.',
    supportingCaseFacts: [
      {
        label: 'Jurisdiction Identified',
        fact: 'Ogun State (Abeokuta Hub)',
        provenance: 'source-backed',
        sourceNames: ['06_IBEDC_Closure_Letter_03Sep.pdf'],
      },
      {
        label: 'Provider & Unresolved Arrears',
        fact: 'IBEDC (₦106,492.50 demanded with disconnection threat)',
        provenance: 'source-backed',
        sourceNames: ['07_IBEDC_August2026_Bill.pdf'],
      },
      {
        label: 'Payment Uncredited',
        fact: '₦64,438.50 paid via USSD on 12 August',
        provenance: 'source-backed',
        sourceNames: ['02_Payment_Receipt_12Aug.png'],
      },
      {
        label: 'Conflicting Provider Responses',
        fact: 'Closure letter claims resolved vs WhatsApp support states still pending review',
        provenance: 'conflict',
        sourceNames: ['06_IBEDC_Closure_Letter_03Sep.pdf', '08_WhatsApp_Support_Chat_07Sep.png'],
      },
    ],
    eligibility: 'Consumers located within Ogun State who have lodged an initial complaint with IBEDC Customer Complaints Unit (CCU-12345) that was closed unresolved, exceeded the 15-day resolution window, or resulted in conflicting closure communications.',
    requiredDocuments: [
      'Proof of initial complaint to IBEDC CCU (Email & Ref: CCU-12345)',
      'Disputed electricity bills showing estimated billing',
      'Proof of payment receipt (TRX-DEMO-982341)',
      'Contradictory closure letters and WhatsApp transcript',
    ],
    steps: [
      'Confirm provider internal complaint was submitted and statutory window has passed',
      'Prepare copies of disputed bills, payment receipts, and provider responses',
      'Submit dispute petition to OGSERC Consumer Affairs Directorate citing account reference and unresolved problem',
      'Attend mediation or regulatory review hearing if convened',
    ],
    officialSource: 'Ogun State Electricity Law 2024 & NERC Intrastate Devolution Order (Order No. NERC/2024/043)',
    sourceUrl: 'https://ogserc.og.gov.ng/regulations/consumer-dispute-resolution',
    lastCheckedDate: '2026-09-21',
    warning: 'Based on the current regulatory information available, this pathway may be relevant. CaseCarry does not provide binding legal counsel or guarantee outcomes.',
    warnings: [
      'Keep copies of all submissions; regulatory review can take 15–30 days.',
      'Request an immediate stay of disconnection while dispute is actively pending before the commission.',
    ],
    uncertainties: [
      'Exact weekly hearing sitting schedules for the Abeokuta disputes tribunal.',
      'Whether hearings are currently conducted in-person or via electronic dispute registry.',
    ],
    whatWeDontKnow: 'Exact weekly hearing sitting schedules for the Abeokuta disputes tribunal and whether hearings are currently conducted in-person or via electronic registry.',
    statusNotes: 'Current 2026 State Regulatory Pathway (Devolved under Electricity Act 2023).',
    confidence: 'high',
    confidenceExplanation: 'Strong relevance match based on verified Ogun State jurisdiction, IBEDC provider, and documented payment and closure conflict.',
    status: 'POTENTIAL',
  },
  {
    id: 'fccpc-consumer-protection',
    name: 'FCCPC (Federal Competition & Consumer Protection Commission)',
    organization: 'FCCPC Nigeria — Southwest Regional Directorate',
    jurisdiction: 'Nigeria (Federal / Southwest Zonal Office)',
    pathwayType: 'consumer_protection',
    whyRelevant: 'The FCCPC has statutory authority under the Federal Competition and Consumer Protection Act (FCCPA 2018) to investigate deceptive business practices, uncredited paid transactions, arbitrary estimated billing, and refusal to rectify proven payments.',
    relevanceReason: 'Applicable based on uncredited payment of ₦64,438.50 and persistent arbitrary estimated charges.',
    supportingCaseFacts: [
      {
        label: 'Consumer Transaction',
        fact: 'Uncredited utility payment of ₦64,438.50',
        provenance: 'source-backed',
        sourceNames: ['02_Payment_Receipt_12Aug.png'],
      },
      {
        label: 'Deceptive Resolution Claim',
        fact: 'Provider issued resolution notice without crediting account',
        provenance: 'source-backed',
        sourceNames: ['06_IBEDC_Closure_Letter_03Sep.pdf'],
      },
    ],
    eligibility: 'Any consumer subjected to arbitrary billing, payment non-reconciliation, or misleading claims of dispute resolution by a regulated service provider.',
    requiredDocuments: [
      'Evidence of paid transaction not credited (Payment gateway receipt)',
      'Correspondence showing service provider claimed resolution without effecting adjustments',
      'CaseCarry Verified Carry-Forward Case Bundle',
    ],
    steps: [
      'File consumer dispute online via FCCPC Portal',
      'Attach CaseCarry carry-forward bundle and proof of payment',
      'FCCPC Consumer Affairs Department initiates investigation and summons provider',
    ],
    officialSource: 'Federal Competition and Consumer Protection Act (FCCPA 2018, Sections 17 & 130) — Consumer Redress Regulations',
    sourceUrl: 'https://fccpc.gov.ng/complaints/',
    lastCheckedDate: '2026-09-21',
    warning: 'Based on current consumer protection laws, this pathway may be relevant. FCCPC can mediate or issue administrative summons.',
    warnings: [
      'FCCPC investigations may run concurrently with sector-specific regulatory reviews.',
    ],
    uncertainties: [
      'Current turnaround time for southwest zonal utility mediation desks.',
    ],
    whatWeDontKnow: 'Current backlog resolution timeline for southwest zonal utility mediation desks.',
    statusNotes: 'Active Federal Consumer Protection Pathway.',
    confidence: 'high',
    confidenceExplanation: 'High relevance match based on uncredited commercial transaction and unfair billing practices.',
    status: 'POTENTIAL',
  },
  {
    id: 'legal-aid-civic-advocate',
    name: 'Community Legal Aid & Civic Consumer Advocacy Desk',
    organization: 'Legal Aid Council of Nigeria / Civic Consumer Rights Initiative',
    jurisdiction: 'Abeokuta / Ogun State Branch',
    pathwayType: 'legal_aid',
    whyRelevant: 'Civil society organizations and the Legal Aid Council provide direct representation and advocacy for citizens facing wrongful utility disconnection, arbitrary billing exploitation, or administrative neglect.',
    relevanceReason: 'Relevant if immediate civic or legal representation is needed against disconnection threats.',
    supportingCaseFacts: [
      {
        label: 'Active Disconnection Threat',
        fact: '10-day disconnection notice active on August bill',
        provenance: 'source-backed',
        sourceNames: ['07_IBEDC_August2026_Bill.pdf'],
      },
    ],
    eligibility: 'Open to residents experiencing persistent utility harassment, wrongful disconnection notices, or administrative neglect.',
    requiredDocuments: [
      'Complete CaseCarry Carry-Forward Bundle',
      'Recent electricity bills and proof of payment',
      'Utility account disconnection notice',
    ],
    steps: [
      'Present CaseCarry carry-forward bundle to Duty Solicitor / Civic Desk',
      'Advocate issues formal legal demand notice to service provider management',
    ],
    officialSource: 'Legal Aid Council of Nigeria Act & Civic Rights Charter',
    sourceUrl: 'https://legalaidcouncil.gov.ng',
    lastCheckedDate: '2026-09-21',
    warning: 'Based on public legal assistance criteria, this pathway may be relevant.',
    uncertainties: [
      'Caseworker availability and caseload capacity at local Abeokuta branch.',
    ],
    whatWeDontKnow: 'Caseworker availability and caseload capacity at local Abeokuta branch.',
    statusNotes: 'Civic & Community Representation Pathway.',
    confidence: 'medium',
    confidenceExplanation: 'Moderate relevance as secondary civic advocacy route.',
    status: 'POTENTIAL',
  },
];

export const SAMPLE_CASE_RECORD = DEMO_CASE;
export const SAMPLE_EVIDENCE_FILES = DEMO_CASE.evidence;
export const SAMPLE_CASE_EVENTS = DEMO_CASE.events;
export const SAMPLE_UNRESOLVED_ISSUE = DEMO_CASE.unresolved;
export const SAMPLE_PATHWAYS = RELEVANT_PATHWAYS;
